"""empty message

Revision ID: 724fbce33975
Revises: 5dba83a29e5c
Create Date: 2020-12-15 15:07:58.171746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724fbce33975'
down_revision = '5dba83a29e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
