"""empty message

Revision ID: aed0cd5d676f
Revises: abb479fcb53d
Create Date: 2020-12-10 03:11:11.770672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed0cd5d676f'
down_revision = 'abb479fcb53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.drop_column('post', 'category')
    # ### end Alembic commands ###
